#!/usr/bin/env python3
"""Build the Boomi API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Connector Deployment': 'Connector Dep.',
    'API Gateway GraphQL': 'API GW GraphQL',
    'Platform Partner': 'Plat. Partner',
    'Agent Control': 'Agent Ctrl',
}

LINES = [
    {
        "name": 'Platform & Management',
        "color": '#3470F4',
        "stations": [
        ('Boomi', (270, 200)),
        ('Platform REST', (430, 175)),
        ('Platform Partner', (610, 165)),
        ('Platform SOAP', (790, 175)),
        ('Agent Control', (970, 200)),
        ],
    },
    {
        "name": 'Integration Tools',
        "color": '#0E9D6E',
        "stations": [
        ('API Management', (270, 320)),
        ('DataHub', (430, 295)),
        ('Event Streams', (610, 295)),
        ('Flow', (800, 320)),
        ],
    },
    {
        "name": 'Connectivity',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Connector Deployment', (640, 470)),
        ('MFT', (760, 555)),
        ('API Gateway GraphQL', (520, 555)),
        ],
    },
]

URL_OVERRIDES = {
    'Boomi': 'https://apis.apis.io/apis/boomi/boomi/',
    'Platform REST': 'https://apis.apis.io/apis/boomi/platform-rest-api/',
    'Platform Partner': 'https://apis.apis.io/apis/boomi/platform-partner-api/',
    'Platform SOAP': 'https://apis.apis.io/apis/boomi/platform-soap-api/',
    'API Management': 'https://apis.apis.io/apis/boomi/api-management-api/',
    'DataHub': 'https://apis.apis.io/apis/boomi/datahub-api/',
    'Event Streams': 'https://apis.apis.io/apis/boomi/event-streams-api/',
    'Flow': 'https://apis.apis.io/apis/boomi/flow-api/',
    'Connector Deployment': 'https://apis.apis.io/apis/boomi/connector-deployment-api/',
    'MFT': 'https://apis.apis.io/apis/boomi/mft-api/',
    'API Gateway GraphQL': 'https://apis.apis.io/apis/boomi/api-gateway-graphql-api/',
    'Agent Control': 'https://apis.apis.io/apis/boomi/agent-control-tower-graphql-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Boomi API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: boomi/openapi · github.com/api-evangelist/boomi',
        out_dir=Path(__file__).resolve().parent,
        out_basename='boomi-subway-map',
        provider_id='boomi',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
